# Generated by Django 4.1.7 on 2023-04-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaneador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escaneador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_ejecucion', models.BooleanField(default=False)),
                ('estrategia', models.CharField(max_length=100)),
            ],
        ),
    ]
