# Generated by Django 4.1.7 on 2023-04-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaneador', '0002_escaneador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_escaneador', models.IntegerField()),
                ('nombre_estrategia', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('precio_entrada', models.CharField(max_length=100)),
            ],
        ),
    ]
