# Generated by Django 4.1.7 on 2023-04-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaneador', '0003_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='movimiento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
